BASIC_AUTH_HEADER = "Basic ..." # Basic auth header: dummy client credentials - Base 64 encoded username:password
DUMMY_TOKEN = "token" # Dummy token returned from the auth endpoint to be used for subsequent requests

# Variables that would normally be environment variables but have to be loaded through secrets for Shuttle
RUST_LOG = "binary-name=debug" # Logging configuration - https://docs.rs/env_logger/latest/env_logger/
DEFAULT_CALLBACK_URL = "https://example.com/api/openadr3/event" # OpenADR 3.0 VEN callback URL, for example Kempower ChargEye