BASIC_AUTH_HEADER = "Basic ..." # Basic auth header: dummy client credentials - Base 64 encoded username:password
DUMMY_TOKEN = "token" # Dummy token returned from the auth endpoint to be used for subsequent requests